[admiral]
items = ["left",
	"color_reverse", "bgcolor_x_cyan", "clock", "fg_color_base", "reverse", "sep",
	"color_reverse", "font_bold", "cur_wksp_main", "font_normal",
	"bg_color_darkgrey", "workspaces", "bgcolor_base", "fgcolor_base"]

[workspaces]
path = "./bspwm_workspaces.sh"

[cur_wksp_main]
path = "./cur_wksp_main"

[clock]
path = "./timedate"
reload = 1

# Formatting

[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true

[bgcolor_base]
path = "echo '%{B-}'"
static = true

[bgcolor_x_darkgrey]
path = "echo '%{B#928374}'"
static = true

[bgcolor_x_cyan]
path = "echo '%{B#8ec07c}'"
static = true

[fgcolor_base]
path = "echo '%{F-}'"
static = true

[color_reverse]
path = "echo '%{R}'"
static = true

[font_normal]
path = "echo '%{T1}'"
static = true

[font_bold]
path = "echo '%{T2}'"
static = true

[sep]
path = "echo $SHELL"
static = true
