[admiral]
items = ["left", "clock", "sep", "cur_wksp_main","sep", "workspaces"]

[workspaces]
path = "./bspwm_workspaces.sh"

[cur_wksp_main]
path = "./cur_wksp_main"

[clock]
path = "./timedate"
reload = 1

# Used for formatting lemonbar
[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true

[sep]
path = "echo '{sep}'"
static = true
