#!/bin/bash

if ! type bspc &> /dev/null; then
	echo "bspc not found"
	exit 1
fi

while read -r line; do
	echo -e "%{B#32302f}%{F#ebdbb2}%{A:kill $(cat ./pid/admiral_xtitle_pid):}%{R}%{T2} $(bspc query -D -d --names) $(xtitle) %{T1}%{R}%{B-}%{A} "
done < <(bspc subscribe report)
# %{B#8ec07c}%{F#32302f}" $HOSTNAME "%{B#ebdbb2}%{F#8ec07c}\ue0b0
