#!/bin/bash

if ! type bspc &> /dev/null; then
	echo "bspc not found"
	exit 1
fi

while read -r line; do
	echo -e "%{B#8ec07c}%{F#32302f}" $HOSTNAME "%{B#ebdbb2}%{F#8ec07c}\ue0b0%{B#32302f}%{F#ebdbb2}%{R}%{T2}%{A:cd ~/.config/lemonbar && ./bar_xtitle:} $(bspc query -D -d --names) %{T1}%{R}%{B#928374}\ue0b0%{A} "
done < <(bspc subscribe report)
