#!/bin/bash

(admiral -c /home/sujit/.config/admiral.d/admiral_xtitle.toml & echo $! >&3) 3>~/.config/admiral.d/pid/admiral_xtitle_pid | lemonbar -F '#ebdbb2' -g x22+10+17 -f -misc-tamzenforpowerline-medium-r-normal--20-145-100-100-c-100-iso8859-1 -f -misc-tamzenforpowerline-bold-r-normal--20-145-100-100-c-100-iso8859-1 | sh
#-B '#32302f' 
