#!/bin/bash

admiral -c /home/void/dotfiles/.config/admiral.d/admiral_main.toml | lemonbar -g 1920x20 -f -uw-ttyp0-medium-r-normal--16-150-75-75-c-80-iso10646-1 -f -uw-ttyp0-medium-r-normal--16-150-75-75-c-80-iso10646-1 -F '#ebdbb2' -a 21 -p | sh &
#-B '#32302f' 3420+10+17
