#!/bin/bash

admiral -c /home/sujit/.config/admiral.d/admiral_main.toml | lemonbar -g 3420x22+10+17 -f -misc-tamzenforpowerline-medium-r-normal--20-145-100-100-c-100-iso8859-1 -f -misc-tamzenforpowerline-bold-r-normal--20-145-100-100-c-100-iso8859-1 -B '#32302f' -F '#ebdbb2' -a 21 -p | sh &
