[admiral]
items = ["clock", "sep",
	 "cur_wksp", "sep",
	 "xtitle", "sep",
	 "workspaces", "sep"]


[workspaces]
path = "/home/sujit/.config/lemonbar/python/scripts/bspwm_workspaces"

[cur_wksp]
path = "/home/sujit/.config/lemonbar/python/scripts/cur_wksp"

[xtitle]
path = "/home/sujit/.config/lemonbar/python/scripts/xtitle"

[clock]
path = "/home/sujit/.config/lemonbar/python/scripts/timedate"
reload = 1

[sep]
path = "echo '{sep}'"
static = true
